# -*- coding: utf-8 -*-
"""Predicted Savings Visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-BwilOFlwyNqlMR8IM92jU-uzm8cemy
"""

import pandas as pd
import plotly.express as px

def visualize_savings_kde(csv_file_path, user_id):
    # Load the data
    df = pd.read_csv(csv_file_path)

    # Filter data for the specified user
    user_data = df[df['customer_id'] == user_id]

    # Create the KDE plot
    fig = px.histogram(user_data, x='individual_savings', nbins=50, histnorm='probability density', title=f'KDE Plot of Savings for User {user_id}')

    # Find the month with the highest savings
    max_savings_month = user_data.loc[user_data['individual_savings'].idxmax(), 'transaction_date']

    # Add marker for the month with highest savings
    fig.add_vline(x=user_data['individual_savings'].max(), line_dash="dash", line_color="red", annotation_text=f'Highest Savings Month: {max_savings_month}')

    # Show the plot
    fig.show()

# Path to the CSV file
csv_file_path = "/content/Age-norm residuals with scores.csv"

# User ID for visualization
user_id = int(input("Enter user ID: "))

# Visualize interactive KDE plot of savings for the specified user
visualize_savings_kde(csv_file_path, user_id)

